# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='depending_on',
            field=models.ManyToManyField(blank=True, default=None, related_name='instance_on_instance', to='servicecatalog.Instance'),
        ),
    ]
