# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0002_auto_20160916_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
