# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0005_auto_20160917_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmethod',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_to_method', to='servicecatalog.Contact'),
        ),
    ]
