# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0009_auto_20160917_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='documentation',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='tickets',
            field=models.URLField(blank=True, null=True),
        ),
    ]
