# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0014_auto_20160917_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_depricated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
