# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0015_auto_20160918_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='is_depricated',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_live',
        ),
        migrations.AddField(
            model_name='module',
            name='state',
            field=models.CharField(choices=[('dev', 'In development'), ('live',
                'Live'), ('depricated', 'Depricated')], default=None,
                max_length=10, null=True, blank=True, )
        ),
    ]
