# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0018_auto_20160918_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='type',
            field=models.CharField(choices=[('lb', 'Loadbalancer'), ('web', 'Web Server'), ('app', 'Application Server'), ('db', 'Database Server'), ('file', 'File Server'), ('token', 'Tokenizer')], default=None, max_length=10),
        ),
    ]
