# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0019_auto_20160919_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='depending_on_hardware',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='depending_on_instance',
        ),
    ]
