# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0021_auto_20160920_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='depending_on_hardware',
            field=models.ManyToManyField(blank=True, default=None, related_name='hardware_on_hardware', through='servicecatalog.hardware_depending_on_hardware', to='servicecatalog.Hardware'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='depending_on_instance',
            field=models.ManyToManyField(blank=True, null=True, related_name='hardware_on_instance', through='servicecatalog.hardware_depending_on_instance', to='servicecatalog.Instance'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
