# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0022_auto_20160920_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware_depending_on_hardware',
            name='hardware_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hardwareFrom', to='servicecatalog.Hardware'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardware_depending_on_hardware',
            name='hardware_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hardwareTo', to='servicecatalog.Hardware'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardware_depending_on_instance',
            name='from_hardware',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fromHardware', to='servicecatalog.Hardware'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardware_depending_on_instance',
            name='to_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toInstance', to='servicecatalog.Instance'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='hardware_depending_on_hardware',
            name='depending_on',
        ),
        migrations.RemoveField(
            model_name='hardware_depending_on_hardware',
            name='hardware',
        ),
        migrations.AlterUniqueTogether(
            name='hardware_depending_on_hardware',
            unique_together=set([('hardware_from', 'hardware_to')]),
        ),
        migrations.RemoveField(
            model_name='hardware_depending_on_instance',
            name='hardware',
        ),
        migrations.RemoveField(
            model_name='hardware_depending_on_instance',
            name='instance',
        ),
        migrations.AlterUniqueTogether(
            name='hardware_depending_on_instance',
            unique_together=set([('from_hardware', 'to_instance')]),
        ),
    ]
