# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0024_auto_20160928_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleWritesToModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_module', to='servicecatalog.Module')),
            ],
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='state',
            field=models.CharField(choices=[('d', 'In development'), ('l', 'Live'), ('X', 'Depricated')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='image',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modulewritestomodule',
            name='payment_methods',
            field=models.ManyToManyField(to='servicecatalog.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='modulewritestomodule',
            name='to_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_module', to='servicecatalog.Module'),
        ),
        migrations.AddField(
            model_name='module',
            name='connected_to_module',
            field=models.ManyToManyField(blank=True, default=None, related_name='module_write_module', through='servicecatalog.ModuleWritesToModule', to='servicecatalog.Module'),
        ),
        migrations.AlterUniqueTogether(
            name='modulewritestomodule',
            unique_together=set([('from_module', 'to_module')]),
        ),
    ]
