# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0025_auto_20160928_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='connected_to_module',
        ),
        migrations.AddField(
            model_name='modulewritestomodule',
            name='access_direction',
            field=models.CharField(choices=[('r', 'Read'), ('w', 'Write'), ('rw', 'Read/Write')], default='rw', max_length=2),
        ),
        migrations.AlterField(
            model_name='modulewritestomodule',
            name='from_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_from_relation', to='servicecatalog.Module'),
        ),
        migrations.AlterField(
            model_name='modulewritestomodule',
            name='to_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_to_relation', to='servicecatalog.Module'),
        ),
        migrations.AlterUniqueTogether(
            name='modulewritestomodule',
            unique_together=set([('from_module', 'to_module', 'access_direction')]),
        ),
    ]
