# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0026_auto_20160928_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='connected_to_module',
            field=models.ManyToManyField(blank=True, default=None, related_name='module_write_module', through='servicecatalog.ModuleWritesToModule', to='servicecatalog.Module'),
        ),
    ]
