# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0028_auto_20160928_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulewritestomodule',
            name='state',
            field=models.CharField(choices=[('d', 'In development'), ('l', 'Live'), ('X', 'Deprecated')], default='l', max_length=1),
        ),
        migrations.AlterField(
            model_name='module',
            name='state',
            field=models.CharField(choices=[('d', 'In development'), ('l', 'Live'), ('X', 'Deprecated')], default='l', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='state',
            field=models.CharField(choices=[('d', 'In development'), ('l', 'Live'), ('X', 'Deprecated')], default='l', max_length=1),
        ),
    ]
