# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0029_auto_20160928_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulewritestomodule',
            name='comment',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
