# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0030_modulewritestomodule_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulewritestomodule',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
