# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0032_auto_20160929_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulewritestomodule',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
