# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0033_auto_20160929_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
