# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0034_auto_20160929_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='css_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
