# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0035_module_css_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name']},
        ),
    ]
