# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0037_auto_20161002_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='external_service',
            field=models.BooleanField(default=False),
        ),
    ]
