# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0038_module_external_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulewritestomodule',
            name='is_online',
            field=models.NullBooleanField(default=None),
        ),
    ]
