# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0039_modulewritestomodule_is_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='external_service',
            new_name='is_service',
        ),
    ]
