# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0040_auto_20161002_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
