# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0041_module_is_external'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulewritestomodule',
            unique_together=set([('from_module', 'to_module', 'access_direction', 'is_online')]),
        ),
    ]
