# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0042_auto_20161002_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='depending_on_hardware',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='depending_on_instance',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='instance',
        ),
        migrations.AlterUniqueTogether(
            name='hardware_depending_on_hardware',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='hardware_depending_on_hardware',
            name='hardware_from',
        ),
        migrations.RemoveField(
            model_name='hardware_depending_on_hardware',
            name='hardware_to',
        ),
        migrations.AlterUniqueTogether(
            name='hardware_depending_on_instance',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='hardware_depending_on_instance',
            name='from_hardware',
        ),
        migrations.RemoveField(
            model_name='hardware_depending_on_instance',
            name='to_instance',
        ),
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='instance',
            name='depending_on',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='location',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='module',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='service_delivery',
        ),
        migrations.DeleteModel(
            name='Hardware',
        ),
        migrations.DeleteModel(
            name='hardware_depending_on_hardware',
        ),
        migrations.DeleteModel(
            name='hardware_depending_on_instance',
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
    ]
