# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0045_auto_20161018_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name'], 'permissions': (('is_owner', 'Is Owner'), ('can_edit', 'Can edit'), ('can_delte', 'Can delete'))},
        ),
    ]
