# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0046_auto_20161018_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name'], 'permissions': (('is_owner', 'Is Owner'),)},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name'], 'permissions': (('is_owner', 'Is Owner'),)},
        ),
    ]
