# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine_manager', '0010_auto_20161020_0932'),
        ('instance_manager', '0006_auto_20161020_0932'),
        ('servicecatalog', '0049_auto_20161020_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmethod',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='module',
            name='owners',
        ),
        migrations.AlterField(
            model_name='modulecontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_manager.Contact'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactMethod',
        ),
    ]
