# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager', '0007_auto_20161020_0758'),
        ('servicecatalog', '0050_auto_20161020_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulecontact',
            old_name='contact_role',
            new_name='role',
        ),
        migrations.AlterUniqueTogether(
            name='modulecontact',
            unique_together=set([('module', 'contact', 'role')]),
        ),
    ]
